# When Habitat starts this service, it'll use the values we define here
# to render the templates we define in our plan's `config` directory.
#
# To learn more about Habitat's configuration features, see the docs at
# https://www.habitat.sh/docs/developing-packages/#add-configuration.

title = "Habitat - The fastest path from code to cloud native."
port = 80

[app]
port = 80

adsf321l;4k`'1;lkj432q0-981345klr tr9023kjtfa;fk: rjq3p48572i43k5j 2435
2435ku 2poi4k;j3
